version: "3.2"
services:
  postgres:
    image: postgres:14
    container_name: products_web_db
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 6
    volumes:
      - ./db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql